global using System.Net.Http.Json;
global using BlazzorEcommerce.Shared;
global using BlazzorEcommerce.Client.Services.ProductService;
global using BlazzorEcommerce.Client.Services.AuthService;
global using Microsoft.AspNetCore.Components.Authorization;
global using BlazzorEcommerce.Client.Services.CartService;
 using BlazzorEcommerce.Client.Services.OrderService;
using BlazzorEcommerce.Client;
using Microsoft.AspNetCore.Components.Web;
using BlazzorEcommerce.Client.Services.CategorySevice;
using Microsoft.AspNetCore.Components.WebAssembly.Hosting;
using Blazored.LocalStorage;
using BlazzorEcommerce.Client.Services.AddressService;

var builder = WebAssemblyHostBuilder.CreateDefault(args);
builder.RootComponents.Add<App>("#app");
builder.RootComponents.Add<HeadOutlet>("head::after");

builder.Services.AddBlazoredLocalStorage();
builder.Services.AddScoped(sp => new HttpClient { BaseAddress = new Uri(builder.HostEnvironment.BaseAddress) });
builder.Services.AddScoped<IProductService, ProductService>();
builder.Services.AddScoped<ICategoryService, CategoryService>();
builder.Services.AddScoped<ICartService, CartService>();
builder.Services.AddScoped<IAuthService, AuthService>();
builder.Services.AddScoped<IOrderService,OrderService>();
builder.Services.AddScoped<IAddressService , AddressService>();
builder.Services.AddOptions();
builder.Services.AddAuthorizationCore();
builder.Services.AddScoped<AuthenticationStateProvider, CustomAuthStateProvider>();
await builder.Build().RunAsync();
